/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_va_server_NativeServer */

#ifndef _Included_com_va_server_NativeServer
#define _Included_com_va_server_NativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_va_server_NativeServer
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_va_server_NativeServer
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_exit
  (JNIEnv *, jobject);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverUpdateKeys
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_serverUpdateKeys
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverUpdateU2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_serverUpdateU2
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverUpdateInput
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_serverUpdateInput
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverUpdateMaskShares
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_serverUpdateMaskShares
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverFinalResult
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_va_server_NativeServer_serverFinalResult
  (JNIEnv *, jobject);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverUpdateV1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_serverUpdateV1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverUpdateDecomStrShares
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_va_server_NativeServer_serverUpdateDecomStrShares
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_va_server_NativeServer
 * Method:    serverFinalDecomStr
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_va_server_NativeServer_serverFinalDecomStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
